# Generated by Django 3.1.2 on 2020-11-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20201112_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
