# Generated by Django 3.1.2 on 2021-06-22 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
